---
services:
  service:
    image: marchagen/papa:latest
    container_name: papad
    restart: unless-stopped
    volumes:
      - ./config/default.yml:/app/config.yml:ro
      - ./media:/media:ro
      - /run/user/1000/pipewire-0:/run/user/1001/pipewire-0
      # If the client communicates with the service via a shared Unix socket, mount the same volume
      - papad-run:/var/run/user/1001/papa

  client:
    image: marchagen/papa:latest
    container_name: papa
    depends_on:
      - service
    # Run the client binary from the same image
    command: ["/bin/sh"]
    restart: "no"
    # If the client communicates with the service via a shared Unix socket, mount the same volume
    volumes:
      - papad-run:/var/run/user/1001/papa

volumes:
  papad-run:
